apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-snapshot-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: csi-snapshot-controller
    role: controller
spec:
  replicas: {{ .Values.csiSnapshotController.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: csi-snapshot-controller
      role: controller
  template:
    metadata:
      annotations:
{{- if .Values.csiSnapshotController.podAnnotations }}
{{ toYaml .Values.csiSnapshotController.podAnnotations | indent 8 }}
{{- end }}
      creationTimestamp: null
      labels:
        app: csi-snapshot-controller
        role: controller
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
    spec:
      containers:
      - name: csi-snapshot-controller
        image: {{ index .Values.images "csi-snapshot-controller" }}
        imagePullPolicy: IfNotPresent
        args:
        - --kubeconfig=/var/lib/csi-snapshot-controller/kubeconfig
        - --leader-election=true
        - --leader-election-namespace=kube-system
{{- if .Values.csiSnapshotController.resources }}
        resources:
{{ toYaml .Values.csiSnapshotController.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: csi-snapshot-controller
          mountPath: /var/lib/csi-snapshot-controller
      volumes:
      - name: csi-snapshot-controller
        secret:
          secretName: csi-snapshot-controller
