{{ if eq .Values.gardener.seed.provider "aws" }}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: lb-readvertiser-parser
  labels:
    fluentbit.gardener/type: "seed"
    fluentbit.gardener.cloud/type: "seed"
spec:
  regex:
    timeKey: time
    timeFormat: "%Y-%m-%dT%H:%M:%SZ"
    regex: '^time="(?<time>\d{4}-\d{2}-\d{2}T[^"]*)"\s+level=(?<severity>\w+)\smsg="(?<log>.*)"'
{{ end}}