{{- if eq .Values.gardener.seed.provider "aws" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  labels:
{{ include "labels" . | indent 4 }}
allowVolumeExpansion: true
provisioner: {{ .Values.config.etcd.storage.provisioner }}
parameters:
  type: gp2
{{- if .Values.config.etcd.storage.encrypted }}
  encrypted: "true"
{{- end }}
{{- end }}
