aws:
  region: eu-west-1

create:
  vpc: true

sshPublicKey: sshkey-12345

clusterName: test-namespace
enableECRAccess: true

vpc:
  id: aws_vpc.vpc.id
  cidr: 10.10.10.10/6
  dhcpDomainName: eu-west-1.compute.internal
  internetGatewayID: aws_internet_gateway.igw.id
  gatewayEndpoints: []

zones:
- name: eu-west-1a
  worker: 10.250.0.0/19
  public: 10.250.96.0/22
  internal: 10.250.112.0/22
# elasticIPAllocationID: eipalloc-123456
- name: eu-west-1b
  worker: 10.250.0.0/19
  public: 10.250.96.0/22
  internal: 10.250.112.0/22
# elasticIPAllocationID: eipalloc-789456

ignoreTags:
  keys: []
  keyPrefixes: []

outputKeys:
  vpcIdKey: vpc_id
  subnetsPublicPrefix: subnet_public_utility_z
  subnetsNodesPrefix: subnet_nodes_z
  securityGroupsNodes: security_group_nodes
  sshKeyName: keyName
  iamInstanceProfileNodes: iamInstanceProfileNodes
  iamInstanceProfileBastions: iamInstanceProfileBastions
  nodesRole: nodes_role_arn
  bastionsRole: bastions_role_arn
