apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: privileged
  name: provider-aws
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-aws-runtime:v1.65.1-dev
      virtualCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-aws-application:v1.65.1-dev
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/provider-aws:v1.65.1-dev
      injectGardenKubeconfig: true
  resources:
  - kind: BackupBucket
    type: aws
  - kind: BackupEntry
    type: aws
  - kind: Bastion
    type: aws
  - kind: ControlPlane
    type: aws
  - kind: DNSRecord
    type: aws-route53
  - kind: Infrastructure
    type: aws
  - kind: Worker
    type: aws
