apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: gardener-extension-provider-aws
  namespace: garden
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: eu.gcr.io/sap-gcp-cp-k8s-stable-hub/examples/landscaper/temp
      componentName: github.com/gardener/gardener-extension-provider-aws
      version: 1.0.0

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
      - name: cluster
        target: "#rh-cluster"

  importDataMappings:
    cloudProfile:
      machineImages:
        - name: gardenlinux
          versions:
            - version: 27.1.0
              classification: "supported"
              cri:
                - name: containerd
                  containerRuntimes:
                    - type: gvisor
              regions:
                - name: eu-north-1
                  ami: ami-0bb8dc8950bb9443c
                - name: ap-south-1
                  ami: ami-0ad05a1ae793d06fa
                - name: eu-west-3
                  ami: ami-04efa08d390e6c1b8
                - name: eu-west-2
                  ami: ami-0d45e63a6e0e64049
                - name: eu-west-1
                  ami: ami-0af0155fee34b4a4e
                - name: ap-northeast-2
                  ami: ami-0b2c6a4ec631bccf9
                - name: ap-northeast-1
                  ami: ami-07ccc13d414bcef3c
                - name: sa-east-1
                  ami: ami-0973e4ec7b8cb9f4f
                - name: ca-central-1
                  ami: ami-0e4c5323dbb3e6935
                - name: ap-southeast-1
                  ami: ami-022ce9ff49b3ea2ab
                - name: ap-southeast-2
                  ami: ami-034a6a56910b96871
                - name: eu-central-1
                  ami: ami-04191efdc08e5aef6
                - name: us-east-1
                  ami: ami-06ad56a1fb921d8f1
                - name: us-east-2
                  ami: ami-0945b5300ed828e38
                - name: us-west-1
                  ami: ami-09a83cb715f5b5637
                - name: us-west-2
                  ami: ami-088e94e12398d7fce
                - name: us-gov-west-1
                  ami: ami-b387b8d2
                - name: us-gov-east-1
                  ami: ami-034a7c8e8a716e47a
      regions: {}
      # overrides:
      # - name: us-gov-west-1
      #   zones:
      #   - name: us-gov-west-1a
      #   - name: us-gov-west-1b
      #   - name: us-gov-west-1c

    kubernetesVersions:
      versions:
      - version: 1.19.2
        classification: "preview"
      - version: 1.19.1
        classification: "supported"
      - version: 1.18.8
        classification: "supported"
      - version: 1.18.5
        classification: "deprecated"
        expirationDate: "2020-12-15T23:59:59Z"
      - version: 1.15.12
        classification: "deprecated"

    controllerRegistration:
      resources: {}
      vpa: {}
      concurrentSyncs: 2200

    imageVectorOverwrite:
    - name: cloud-controller-manager
      sourceRepository: github.com/kubernetes/kubernetes
      repository: k8s.gcr.io/hyperkube
      targetVersion: "< 1.17"
    - name: cloud-controller-manager
      sourceRepository: github.com/gardener/cloud-provider-aws
      repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-aws
      tag: "v1.17.15"
      targetVersion: "1.17.x"
    - name: cloud-controller-manager
      sourceRepository: github.com/gardener/cloud-provider-aws
      repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-aws
      tag: "v1.18.13"
      targetVersion: "1.18.x"
    - name: cloud-controller-manager
      sourceRepository: github.com/gardener/cloud-provider-aws
      repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-aws
      tag: "v1.19.5"
      targetVersion: "1.19.x"