# with kubernetes >= 1.33 a deny all rule for the kube-system namespace is applied by default
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aws.extensions.gardener.cloud--allow-metadata-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      aws.extension.gardener.cloud/allow-metadata-access: "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 169.254.169.254/32
      ports:
        - protocol: TCP
          port: 80