{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: machine-controller-manager-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: machine-controller-manager
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
    - containerName: machine-controller-manager-provider-aws
      minAllowed:
        cpu: {{ .Values.resources.mcmProviderAWS.requests.cpu }}
        memory: {{ .Values.resources.mcmProviderAWS.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.mcmProviderAWS.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.mcmProviderAWS.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: aws-machine-controller-manager
      minAllowed:
        cpu: {{ .Values.resources.mcm.requests.cpu }}
        memory: {{ .Values.resources.mcm.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.mcm.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.mcm.maxAllowed.memory }}
      controlledValues: RequestsOnly
{{- end }}
