{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.secret.labels }}
  labels:
{{ toYaml $machineClass.secret.labels | indent 4 }}
{{- end }}
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.labels }}
  labels:
{{ toYaml $machineClass.labels | indent 4 }}
{{- end }}
{{- if $machineClass.nodeTemplate }}
nodeTemplate:
  capacity:
{{ toYaml $machineClass.nodeTemplate.capacity | indent 4 }}
  instanceType: {{ $machineClass.nodeTemplate.instanceType }}
  region: {{ $machineClass.nodeTemplate.region }}
  zone: {{ $machineClass.nodeTemplate.zone }}
{{- end }}
providerSpec:
  ami: {{ $machineClass.ami }}
  region: {{ $machineClass.region }}
  machineType: {{ $machineClass.machineType }}
  srcAndDstChecksEnabled: {{ $machineClass.srcAndDstChecksEnabled }}
  iam:
{{- if $machineClass.iamInstanceProfile.name }}
    name: {{ $machineClass.iamInstanceProfile.name }}
{{- end }}
{{- if $machineClass.iamInstanceProfile.arn }}
    arn: {{ $machineClass.iamInstanceProfile.arn }}
{{- end }}
  keyName: {{ $machineClass.keyName }}
  networkInterfaces:
{{ toYaml $machineClass.networkInterfaces | indent 2 }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
  blockDevices:
{{ toYaml $machineClass.blockDevices | indent 2 }}
{{- if $machineClass.instanceMetadata }}
  instanceMetadata:
    {{- if $machineClass.instanceMetadata.httpEndpoint }}
    httpEndpoint: {{ $machineClass.instanceMetadata.httpEndpoint }}
    {{- end }}
    {{- if $machineClass.instanceMetadata.httpPutResponseHopLimit }}
    httpPutResponseHopLimit: {{ $machineClass.instanceMetadata.httpPutResponseHopLimit }}
    {{- end }}
    {{- if $machineClass.instanceMetadata.httpTokens }}
    httpTokens: {{ $machineClass.instanceMetadata.httpTokens }}
    {{- end }}
{{- end }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
credentialsSecretRef:
  name: {{ $machineClass.credentialsSecretRef.name }}
  namespace: {{ $machineClass.credentialsSecretRef.namespace }}
provider: "AWS"
{{- end }}
