apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap # only one currently available
  fileSystemId: {{ .Values.fileSystemID }}
  directoryPerms: "700"