#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."

"$SOURCE_PATH"/vendor/github.com/gardener/gardener/hack/.ci/component_descriptor "$SOURCE_PATH"

echo "> Building component provider-aws"

CA_PATH="$(mktemp -d)"
mv "$COMPONENT_DESCRIPTOR_PATH" "$CA_PATH"
component-cli ca "${CA_PATH}" "${CTF_PATH}" \
    -r  "$SOURCE_PATH"/.landscaper/resources.yaml \
    VERSION=${EFFECTIVE_VERSION}
