//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	aws "github.com/gardener/gardener-extension-provider-aws/pkg/apis/aws"
	v1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	extensionsv1alpha1 "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BackupBucketConfig)(nil), (*aws.BackupBucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BackupBucketConfig_To_aws_BackupBucketConfig(a.(*BackupBucketConfig), b.(*aws.BackupBucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.BackupBucketConfig)(nil), (*BackupBucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(a.(*aws.BackupBucketConfig), b.(*BackupBucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*aws.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_aws_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*aws.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*aws.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*aws.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_aws_CloudProfileConfig(a.(*CloudProfileConfig), b.(*aws.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*aws.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*aws.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_aws_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*aws.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*aws.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CpuOptions)(nil), (*aws.CpuOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CpuOptions_To_aws_CpuOptions(a.(*CpuOptions), b.(*aws.CpuOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.CpuOptions)(nil), (*CpuOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_CpuOptions_To_v1alpha1_CpuOptions(a.(*aws.CpuOptions), b.(*CpuOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataVolume)(nil), (*aws.DataVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DataVolume_To_aws_DataVolume(a.(*DataVolume), b.(*aws.DataVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.DataVolume)(nil), (*DataVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_DataVolume_To_v1alpha1_DataVolume(a.(*aws.DataVolume), b.(*DataVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DualStack)(nil), (*aws.DualStack)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DualStack_To_aws_DualStack(a.(*DualStack), b.(*aws.DualStack), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.DualStack)(nil), (*DualStack)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_DualStack_To_v1alpha1_DualStack(a.(*aws.DualStack), b.(*DualStack), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EC2)(nil), (*aws.EC2)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EC2_To_aws_EC2(a.(*EC2), b.(*aws.EC2), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.EC2)(nil), (*EC2)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_EC2_To_v1alpha1_EC2(a.(*aws.EC2), b.(*EC2), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ElasticFileSystemConfig)(nil), (*aws.ElasticFileSystemConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ElasticFileSystemConfig_To_aws_ElasticFileSystemConfig(a.(*ElasticFileSystemConfig), b.(*aws.ElasticFileSystemConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.ElasticFileSystemConfig)(nil), (*ElasticFileSystemConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_ElasticFileSystemConfig_To_v1alpha1_ElasticFileSystemConfig(a.(*aws.ElasticFileSystemConfig), b.(*ElasticFileSystemConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ElasticFileSystemStatus)(nil), (*aws.ElasticFileSystemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ElasticFileSystemStatus_To_aws_ElasticFileSystemStatus(a.(*ElasticFileSystemStatus), b.(*aws.ElasticFileSystemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.ElasticFileSystemStatus)(nil), (*ElasticFileSystemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_ElasticFileSystemStatus_To_v1alpha1_ElasticFileSystemStatus(a.(*aws.ElasticFileSystemStatus), b.(*ElasticFileSystemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IAM)(nil), (*aws.IAM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IAM_To_aws_IAM(a.(*IAM), b.(*aws.IAM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.IAM)(nil), (*IAM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_IAM_To_v1alpha1_IAM(a.(*aws.IAM), b.(*IAM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IAMInstanceProfile)(nil), (*aws.IAMInstanceProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IAMInstanceProfile_To_aws_IAMInstanceProfile(a.(*IAMInstanceProfile), b.(*aws.IAMInstanceProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.IAMInstanceProfile)(nil), (*IAMInstanceProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_IAMInstanceProfile_To_v1alpha1_IAMInstanceProfile(a.(*aws.IAMInstanceProfile), b.(*IAMInstanceProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IgnoreTags)(nil), (*aws.IgnoreTags)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IgnoreTags_To_aws_IgnoreTags(a.(*IgnoreTags), b.(*aws.IgnoreTags), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.IgnoreTags)(nil), (*IgnoreTags)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_IgnoreTags_To_v1alpha1_IgnoreTags(a.(*aws.IgnoreTags), b.(*IgnoreTags), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImmutableConfig)(nil), (*aws.ImmutableConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImmutableConfig_To_aws_ImmutableConfig(a.(*ImmutableConfig), b.(*aws.ImmutableConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.ImmutableConfig)(nil), (*ImmutableConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_ImmutableConfig_To_v1alpha1_ImmutableConfig(a.(*aws.ImmutableConfig), b.(*ImmutableConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*aws.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_aws_InfrastructureConfig(a.(*InfrastructureConfig), b.(*aws.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*aws.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureState)(nil), (*aws.InfrastructureState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureState_To_aws_InfrastructureState(a.(*InfrastructureState), b.(*aws.InfrastructureState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.InfrastructureState)(nil), (*InfrastructureState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_InfrastructureState_To_v1alpha1_InfrastructureState(a.(*aws.InfrastructureState), b.(*InfrastructureState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*aws.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_aws_InfrastructureStatus(a.(*InfrastructureStatus), b.(*aws.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*aws.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceMetadataOptions)(nil), (*aws.InstanceMetadataOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstanceMetadataOptions_To_aws_InstanceMetadataOptions(a.(*InstanceMetadataOptions), b.(*aws.InstanceMetadataOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.InstanceMetadataOptions)(nil), (*InstanceMetadataOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(a.(*aws.InstanceMetadataOptions), b.(*InstanceMetadataOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceProfile)(nil), (*aws.InstanceProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstanceProfile_To_aws_InstanceProfile(a.(*InstanceProfile), b.(*aws.InstanceProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.InstanceProfile)(nil), (*InstanceProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_InstanceProfile_To_v1alpha1_InstanceProfile(a.(*aws.InstanceProfile), b.(*InstanceProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LoadBalancerControllerConfig)(nil), (*aws.LoadBalancerControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LoadBalancerControllerConfig_To_aws_LoadBalancerControllerConfig(a.(*LoadBalancerControllerConfig), b.(*aws.LoadBalancerControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.LoadBalancerControllerConfig)(nil), (*LoadBalancerControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_LoadBalancerControllerConfig_To_v1alpha1_LoadBalancerControllerConfig(a.(*aws.LoadBalancerControllerConfig), b.(*LoadBalancerControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*aws.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_aws_MachineImage(a.(*MachineImage), b.(*aws.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_MachineImage_To_v1alpha1_MachineImage(a.(*aws.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageFlavor)(nil), (*aws.MachineImageFlavor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageFlavor_To_aws_MachineImageFlavor(a.(*MachineImageFlavor), b.(*aws.MachineImageFlavor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.MachineImageFlavor)(nil), (*MachineImageFlavor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(a.(*aws.MachineImageFlavor), b.(*MachineImageFlavor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*aws.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_aws_MachineImageVersion(a.(*MachineImageVersion), b.(*aws.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*aws.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*aws.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_aws_MachineImages(a.(*MachineImages), b.(*aws.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_MachineImages_To_v1alpha1_MachineImages(a.(*aws.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Networks)(nil), (*aws.Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Networks_To_aws_Networks(a.(*Networks), b.(*aws.Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.Networks)(nil), (*Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_Networks_To_v1alpha1_Networks(a.(*aws.Networks), b.(*Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionAMIMapping)(nil), (*aws.RegionAMIMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegionAMIMapping_To_aws_RegionAMIMapping(a.(*RegionAMIMapping), b.(*aws.RegionAMIMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.RegionAMIMapping)(nil), (*RegionAMIMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_RegionAMIMapping_To_v1alpha1_RegionAMIMapping(a.(*aws.RegionAMIMapping), b.(*RegionAMIMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Role)(nil), (*aws.Role)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Role_To_aws_Role(a.(*Role), b.(*aws.Role), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.Role)(nil), (*Role)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_Role_To_v1alpha1_Role(a.(*aws.Role), b.(*Role), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroup)(nil), (*aws.SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroup_To_aws_SecurityGroup(a.(*SecurityGroup), b.(*aws.SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.SecurityGroup)(nil), (*SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_SecurityGroup_To_v1alpha1_SecurityGroup(a.(*aws.SecurityGroup), b.(*SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Storage)(nil), (*aws.Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Storage_To_aws_Storage(a.(*Storage), b.(*aws.Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.Storage)(nil), (*Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_Storage_To_v1alpha1_Storage(a.(*aws.Storage), b.(*Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subnet)(nil), (*aws.Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Subnet_To_aws_Subnet(a.(*Subnet), b.(*aws.Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.Subnet)(nil), (*Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_Subnet_To_v1alpha1_Subnet(a.(*aws.Subnet), b.(*Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPC)(nil), (*aws.VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPC_To_aws_VPC(a.(*VPC), b.(*aws.VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.VPC)(nil), (*VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_VPC_To_v1alpha1_VPC(a.(*aws.VPC), b.(*VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCStatus)(nil), (*aws.VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCStatus_To_aws_VPCStatus(a.(*VPCStatus), b.(*aws.VPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.VPCStatus)(nil), (*VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_VPCStatus_To_v1alpha1_VPCStatus(a.(*aws.VPCStatus), b.(*VPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Volume)(nil), (*aws.Volume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Volume_To_aws_Volume(a.(*Volume), b.(*aws.Volume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.Volume)(nil), (*Volume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_Volume_To_v1alpha1_Volume(a.(*aws.Volume), b.(*Volume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerConfig)(nil), (*aws.WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerConfig_To_aws_WorkerConfig(a.(*WorkerConfig), b.(*aws.WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.WorkerConfig)(nil), (*WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_WorkerConfig_To_v1alpha1_WorkerConfig(a.(*aws.WorkerConfig), b.(*WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*aws.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_aws_WorkerStatus(a.(*WorkerStatus), b.(*aws.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*aws.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentityConfig)(nil), (*aws.WorkloadIdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkloadIdentityConfig_To_aws_WorkloadIdentityConfig(a.(*WorkloadIdentityConfig), b.(*aws.WorkloadIdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.WorkloadIdentityConfig)(nil), (*WorkloadIdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(a.(*aws.WorkloadIdentityConfig), b.(*WorkloadIdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Zone)(nil), (*aws.Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Zone_To_aws_Zone(a.(*Zone), b.(*aws.Zone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*aws.Zone)(nil), (*Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_aws_Zone_To_v1alpha1_Zone(a.(*aws.Zone), b.(*Zone), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BackupBucketConfig_To_aws_BackupBucketConfig(in *BackupBucketConfig, out *aws.BackupBucketConfig, s conversion.Scope) error {
	out.Immutability = (*aws.ImmutableConfig)(unsafe.Pointer(in.Immutability))
	return nil
}

// Convert_v1alpha1_BackupBucketConfig_To_aws_BackupBucketConfig is an autogenerated conversion function.
func Convert_v1alpha1_BackupBucketConfig_To_aws_BackupBucketConfig(in *BackupBucketConfig, out *aws.BackupBucketConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_BackupBucketConfig_To_aws_BackupBucketConfig(in, out, s)
}

func autoConvert_aws_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in *aws.BackupBucketConfig, out *BackupBucketConfig, s conversion.Scope) error {
	out.Immutability = (*ImmutableConfig)(unsafe.Pointer(in.Immutability))
	return nil
}

// Convert_aws_BackupBucketConfig_To_v1alpha1_BackupBucketConfig is an autogenerated conversion function.
func Convert_aws_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in *aws.BackupBucketConfig, out *BackupBucketConfig, s conversion.Scope) error {
	return autoConvert_aws_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_aws_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *aws.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.UseCustomRouteController = (*bool)(unsafe.Pointer(in.UseCustomRouteController))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_aws_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_aws_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *aws.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_aws_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_aws_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *aws.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.UseCustomRouteController = (*bool)(unsafe.Pointer(in.UseCustomRouteController))
	return nil
}

// Convert_aws_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_aws_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *aws.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_aws_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_aws_CloudProfileConfig(in *CloudProfileConfig, out *aws.CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]aws.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_aws_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_aws_CloudProfileConfig(in *CloudProfileConfig, out *aws.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_aws_CloudProfileConfig(in, out, s)
}

func autoConvert_aws_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *aws.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_aws_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_aws_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *aws.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_aws_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_aws_ControlPlaneConfig(in *ControlPlaneConfig, out *aws.ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*aws.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.LoadBalancerController = (*aws.LoadBalancerControllerConfig)(unsafe.Pointer(in.LoadBalancerController))
	out.Storage = (*aws.Storage)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_aws_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_aws_ControlPlaneConfig(in *ControlPlaneConfig, out *aws.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_aws_ControlPlaneConfig(in, out, s)
}

func autoConvert_aws_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *aws.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.LoadBalancerController = (*LoadBalancerControllerConfig)(unsafe.Pointer(in.LoadBalancerController))
	out.Storage = (*Storage)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_aws_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_aws_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *aws.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_aws_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_CpuOptions_To_aws_CpuOptions(in *CpuOptions, out *aws.CpuOptions, s conversion.Scope) error {
	out.CoreCount = (*int64)(unsafe.Pointer(in.CoreCount))
	out.ThreadsPerCore = (*int64)(unsafe.Pointer(in.ThreadsPerCore))
	return nil
}

// Convert_v1alpha1_CpuOptions_To_aws_CpuOptions is an autogenerated conversion function.
func Convert_v1alpha1_CpuOptions_To_aws_CpuOptions(in *CpuOptions, out *aws.CpuOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_CpuOptions_To_aws_CpuOptions(in, out, s)
}

func autoConvert_aws_CpuOptions_To_v1alpha1_CpuOptions(in *aws.CpuOptions, out *CpuOptions, s conversion.Scope) error {
	out.CoreCount = (*int64)(unsafe.Pointer(in.CoreCount))
	out.ThreadsPerCore = (*int64)(unsafe.Pointer(in.ThreadsPerCore))
	return nil
}

// Convert_aws_CpuOptions_To_v1alpha1_CpuOptions is an autogenerated conversion function.
func Convert_aws_CpuOptions_To_v1alpha1_CpuOptions(in *aws.CpuOptions, out *CpuOptions, s conversion.Scope) error {
	return autoConvert_aws_CpuOptions_To_v1alpha1_CpuOptions(in, out, s)
}

func autoConvert_v1alpha1_DataVolume_To_aws_DataVolume(in *DataVolume, out *aws.DataVolume, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_Volume_To_aws_Volume(&in.Volume, &out.Volume, s); err != nil {
		return err
	}
	out.SnapshotID = (*string)(unsafe.Pointer(in.SnapshotID))
	return nil
}

// Convert_v1alpha1_DataVolume_To_aws_DataVolume is an autogenerated conversion function.
func Convert_v1alpha1_DataVolume_To_aws_DataVolume(in *DataVolume, out *aws.DataVolume, s conversion.Scope) error {
	return autoConvert_v1alpha1_DataVolume_To_aws_DataVolume(in, out, s)
}

func autoConvert_aws_DataVolume_To_v1alpha1_DataVolume(in *aws.DataVolume, out *DataVolume, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_aws_Volume_To_v1alpha1_Volume(&in.Volume, &out.Volume, s); err != nil {
		return err
	}
	out.SnapshotID = (*string)(unsafe.Pointer(in.SnapshotID))
	return nil
}

// Convert_aws_DataVolume_To_v1alpha1_DataVolume is an autogenerated conversion function.
func Convert_aws_DataVolume_To_v1alpha1_DataVolume(in *aws.DataVolume, out *DataVolume, s conversion.Scope) error {
	return autoConvert_aws_DataVolume_To_v1alpha1_DataVolume(in, out, s)
}

func autoConvert_v1alpha1_DualStack_To_aws_DualStack(in *DualStack, out *aws.DualStack, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_DualStack_To_aws_DualStack is an autogenerated conversion function.
func Convert_v1alpha1_DualStack_To_aws_DualStack(in *DualStack, out *aws.DualStack, s conversion.Scope) error {
	return autoConvert_v1alpha1_DualStack_To_aws_DualStack(in, out, s)
}

func autoConvert_aws_DualStack_To_v1alpha1_DualStack(in *aws.DualStack, out *DualStack, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_aws_DualStack_To_v1alpha1_DualStack is an autogenerated conversion function.
func Convert_aws_DualStack_To_v1alpha1_DualStack(in *aws.DualStack, out *DualStack, s conversion.Scope) error {
	return autoConvert_aws_DualStack_To_v1alpha1_DualStack(in, out, s)
}

func autoConvert_v1alpha1_EC2_To_aws_EC2(in *EC2, out *aws.EC2, s conversion.Scope) error {
	out.KeyName = in.KeyName
	return nil
}

// Convert_v1alpha1_EC2_To_aws_EC2 is an autogenerated conversion function.
func Convert_v1alpha1_EC2_To_aws_EC2(in *EC2, out *aws.EC2, s conversion.Scope) error {
	return autoConvert_v1alpha1_EC2_To_aws_EC2(in, out, s)
}

func autoConvert_aws_EC2_To_v1alpha1_EC2(in *aws.EC2, out *EC2, s conversion.Scope) error {
	out.KeyName = in.KeyName
	return nil
}

// Convert_aws_EC2_To_v1alpha1_EC2 is an autogenerated conversion function.
func Convert_aws_EC2_To_v1alpha1_EC2(in *aws.EC2, out *EC2, s conversion.Scope) error {
	return autoConvert_aws_EC2_To_v1alpha1_EC2(in, out, s)
}

func autoConvert_v1alpha1_ElasticFileSystemConfig_To_aws_ElasticFileSystemConfig(in *ElasticFileSystemConfig, out *aws.ElasticFileSystemConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_v1alpha1_ElasticFileSystemConfig_To_aws_ElasticFileSystemConfig is an autogenerated conversion function.
func Convert_v1alpha1_ElasticFileSystemConfig_To_aws_ElasticFileSystemConfig(in *ElasticFileSystemConfig, out *aws.ElasticFileSystemConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticFileSystemConfig_To_aws_ElasticFileSystemConfig(in, out, s)
}

func autoConvert_aws_ElasticFileSystemConfig_To_v1alpha1_ElasticFileSystemConfig(in *aws.ElasticFileSystemConfig, out *ElasticFileSystemConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_aws_ElasticFileSystemConfig_To_v1alpha1_ElasticFileSystemConfig is an autogenerated conversion function.
func Convert_aws_ElasticFileSystemConfig_To_v1alpha1_ElasticFileSystemConfig(in *aws.ElasticFileSystemConfig, out *ElasticFileSystemConfig, s conversion.Scope) error {
	return autoConvert_aws_ElasticFileSystemConfig_To_v1alpha1_ElasticFileSystemConfig(in, out, s)
}

func autoConvert_v1alpha1_ElasticFileSystemStatus_To_aws_ElasticFileSystemStatus(in *ElasticFileSystemStatus, out *aws.ElasticFileSystemStatus, s conversion.Scope) error {
	out.ID = in.ID
	return nil
}

// Convert_v1alpha1_ElasticFileSystemStatus_To_aws_ElasticFileSystemStatus is an autogenerated conversion function.
func Convert_v1alpha1_ElasticFileSystemStatus_To_aws_ElasticFileSystemStatus(in *ElasticFileSystemStatus, out *aws.ElasticFileSystemStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticFileSystemStatus_To_aws_ElasticFileSystemStatus(in, out, s)
}

func autoConvert_aws_ElasticFileSystemStatus_To_v1alpha1_ElasticFileSystemStatus(in *aws.ElasticFileSystemStatus, out *ElasticFileSystemStatus, s conversion.Scope) error {
	out.ID = in.ID
	return nil
}

// Convert_aws_ElasticFileSystemStatus_To_v1alpha1_ElasticFileSystemStatus is an autogenerated conversion function.
func Convert_aws_ElasticFileSystemStatus_To_v1alpha1_ElasticFileSystemStatus(in *aws.ElasticFileSystemStatus, out *ElasticFileSystemStatus, s conversion.Scope) error {
	return autoConvert_aws_ElasticFileSystemStatus_To_v1alpha1_ElasticFileSystemStatus(in, out, s)
}

func autoConvert_v1alpha1_IAM_To_aws_IAM(in *IAM, out *aws.IAM, s conversion.Scope) error {
	out.InstanceProfiles = *(*[]aws.InstanceProfile)(unsafe.Pointer(&in.InstanceProfiles))
	out.Roles = *(*[]aws.Role)(unsafe.Pointer(&in.Roles))
	return nil
}

// Convert_v1alpha1_IAM_To_aws_IAM is an autogenerated conversion function.
func Convert_v1alpha1_IAM_To_aws_IAM(in *IAM, out *aws.IAM, s conversion.Scope) error {
	return autoConvert_v1alpha1_IAM_To_aws_IAM(in, out, s)
}

func autoConvert_aws_IAM_To_v1alpha1_IAM(in *aws.IAM, out *IAM, s conversion.Scope) error {
	out.InstanceProfiles = *(*[]InstanceProfile)(unsafe.Pointer(&in.InstanceProfiles))
	out.Roles = *(*[]Role)(unsafe.Pointer(&in.Roles))
	return nil
}

// Convert_aws_IAM_To_v1alpha1_IAM is an autogenerated conversion function.
func Convert_aws_IAM_To_v1alpha1_IAM(in *aws.IAM, out *IAM, s conversion.Scope) error {
	return autoConvert_aws_IAM_To_v1alpha1_IAM(in, out, s)
}

func autoConvert_v1alpha1_IAMInstanceProfile_To_aws_IAMInstanceProfile(in *IAMInstanceProfile, out *aws.IAMInstanceProfile, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ARN = (*string)(unsafe.Pointer(in.ARN))
	return nil
}

// Convert_v1alpha1_IAMInstanceProfile_To_aws_IAMInstanceProfile is an autogenerated conversion function.
func Convert_v1alpha1_IAMInstanceProfile_To_aws_IAMInstanceProfile(in *IAMInstanceProfile, out *aws.IAMInstanceProfile, s conversion.Scope) error {
	return autoConvert_v1alpha1_IAMInstanceProfile_To_aws_IAMInstanceProfile(in, out, s)
}

func autoConvert_aws_IAMInstanceProfile_To_v1alpha1_IAMInstanceProfile(in *aws.IAMInstanceProfile, out *IAMInstanceProfile, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ARN = (*string)(unsafe.Pointer(in.ARN))
	return nil
}

// Convert_aws_IAMInstanceProfile_To_v1alpha1_IAMInstanceProfile is an autogenerated conversion function.
func Convert_aws_IAMInstanceProfile_To_v1alpha1_IAMInstanceProfile(in *aws.IAMInstanceProfile, out *IAMInstanceProfile, s conversion.Scope) error {
	return autoConvert_aws_IAMInstanceProfile_To_v1alpha1_IAMInstanceProfile(in, out, s)
}

func autoConvert_v1alpha1_IgnoreTags_To_aws_IgnoreTags(in *IgnoreTags, out *aws.IgnoreTags, s conversion.Scope) error {
	out.Keys = *(*[]string)(unsafe.Pointer(&in.Keys))
	out.KeyPrefixes = *(*[]string)(unsafe.Pointer(&in.KeyPrefixes))
	return nil
}

// Convert_v1alpha1_IgnoreTags_To_aws_IgnoreTags is an autogenerated conversion function.
func Convert_v1alpha1_IgnoreTags_To_aws_IgnoreTags(in *IgnoreTags, out *aws.IgnoreTags, s conversion.Scope) error {
	return autoConvert_v1alpha1_IgnoreTags_To_aws_IgnoreTags(in, out, s)
}

func autoConvert_aws_IgnoreTags_To_v1alpha1_IgnoreTags(in *aws.IgnoreTags, out *IgnoreTags, s conversion.Scope) error {
	out.Keys = *(*[]string)(unsafe.Pointer(&in.Keys))
	out.KeyPrefixes = *(*[]string)(unsafe.Pointer(&in.KeyPrefixes))
	return nil
}

// Convert_aws_IgnoreTags_To_v1alpha1_IgnoreTags is an autogenerated conversion function.
func Convert_aws_IgnoreTags_To_v1alpha1_IgnoreTags(in *aws.IgnoreTags, out *IgnoreTags, s conversion.Scope) error {
	return autoConvert_aws_IgnoreTags_To_v1alpha1_IgnoreTags(in, out, s)
}

func autoConvert_v1alpha1_ImmutableConfig_To_aws_ImmutableConfig(in *ImmutableConfig, out *aws.ImmutableConfig, s conversion.Scope) error {
	out.RetentionType = aws.RetentionType(in.RetentionType)
	out.RetentionPeriod = in.RetentionPeriod
	out.Mode = aws.ModeType(in.Mode)
	return nil
}

// Convert_v1alpha1_ImmutableConfig_To_aws_ImmutableConfig is an autogenerated conversion function.
func Convert_v1alpha1_ImmutableConfig_To_aws_ImmutableConfig(in *ImmutableConfig, out *aws.ImmutableConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImmutableConfig_To_aws_ImmutableConfig(in, out, s)
}

func autoConvert_aws_ImmutableConfig_To_v1alpha1_ImmutableConfig(in *aws.ImmutableConfig, out *ImmutableConfig, s conversion.Scope) error {
	out.RetentionType = RetentionType(in.RetentionType)
	out.RetentionPeriod = in.RetentionPeriod
	out.Mode = ModeType(in.Mode)
	return nil
}

// Convert_aws_ImmutableConfig_To_v1alpha1_ImmutableConfig is an autogenerated conversion function.
func Convert_aws_ImmutableConfig_To_v1alpha1_ImmutableConfig(in *aws.ImmutableConfig, out *ImmutableConfig, s conversion.Scope) error {
	return autoConvert_aws_ImmutableConfig_To_v1alpha1_ImmutableConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_aws_InfrastructureConfig(in *InfrastructureConfig, out *aws.InfrastructureConfig, s conversion.Scope) error {
	out.EnableECRAccess = (*bool)(unsafe.Pointer(in.EnableECRAccess))
	out.DualStack = (*aws.DualStack)(unsafe.Pointer(in.DualStack))
	if err := Convert_v1alpha1_Networks_To_aws_Networks(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.IgnoreTags = (*aws.IgnoreTags)(unsafe.Pointer(in.IgnoreTags))
	out.EnableDedicatedTenancyForVPC = (*bool)(unsafe.Pointer(in.EnableDedicatedTenancyForVPC))
	out.ElasticFileSystem = (*aws.ElasticFileSystemConfig)(unsafe.Pointer(in.ElasticFileSystem))
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_aws_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_aws_InfrastructureConfig(in *InfrastructureConfig, out *aws.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_aws_InfrastructureConfig(in, out, s)
}

func autoConvert_aws_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *aws.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	out.EnableECRAccess = (*bool)(unsafe.Pointer(in.EnableECRAccess))
	out.DualStack = (*DualStack)(unsafe.Pointer(in.DualStack))
	if err := Convert_aws_Networks_To_v1alpha1_Networks(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.IgnoreTags = (*IgnoreTags)(unsafe.Pointer(in.IgnoreTags))
	out.EnableDedicatedTenancyForVPC = (*bool)(unsafe.Pointer(in.EnableDedicatedTenancyForVPC))
	out.ElasticFileSystem = (*ElasticFileSystemConfig)(unsafe.Pointer(in.ElasticFileSystem))
	return nil
}

// Convert_aws_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_aws_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *aws.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_aws_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureState_To_aws_InfrastructureState(in *InfrastructureState, out *aws.InfrastructureState, s conversion.Scope) error {
	out.Data = *(*map[string]string)(unsafe.Pointer(&in.Data))
	return nil
}

// Convert_v1alpha1_InfrastructureState_To_aws_InfrastructureState is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureState_To_aws_InfrastructureState(in *InfrastructureState, out *aws.InfrastructureState, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureState_To_aws_InfrastructureState(in, out, s)
}

func autoConvert_aws_InfrastructureState_To_v1alpha1_InfrastructureState(in *aws.InfrastructureState, out *InfrastructureState, s conversion.Scope) error {
	out.Data = *(*map[string]string)(unsafe.Pointer(&in.Data))
	return nil
}

// Convert_aws_InfrastructureState_To_v1alpha1_InfrastructureState is an autogenerated conversion function.
func Convert_aws_InfrastructureState_To_v1alpha1_InfrastructureState(in *aws.InfrastructureState, out *InfrastructureState, s conversion.Scope) error {
	return autoConvert_aws_InfrastructureState_To_v1alpha1_InfrastructureState(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_aws_InfrastructureStatus(in *InfrastructureStatus, out *aws.InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_EC2_To_aws_EC2(&in.EC2, &out.EC2, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_IAM_To_aws_IAM(&in.IAM, &out.IAM, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCStatus_To_aws_VPCStatus(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ElasticFileSystemStatus_To_aws_ElasticFileSystemStatus(&in.ElasticFileSystem, &out.ElasticFileSystem, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_aws_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_aws_InfrastructureStatus(in *InfrastructureStatus, out *aws.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_aws_InfrastructureStatus(in, out, s)
}

func autoConvert_aws_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *aws.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_aws_EC2_To_v1alpha1_EC2(&in.EC2, &out.EC2, s); err != nil {
		return err
	}
	if err := Convert_aws_IAM_To_v1alpha1_IAM(&in.IAM, &out.IAM, s); err != nil {
		return err
	}
	if err := Convert_aws_VPCStatus_To_v1alpha1_VPCStatus(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	if err := Convert_aws_ElasticFileSystemStatus_To_v1alpha1_ElasticFileSystemStatus(&in.ElasticFileSystem, &out.ElasticFileSystem, s); err != nil {
		return err
	}
	return nil
}

// Convert_aws_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_aws_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *aws.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_aws_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_InstanceMetadataOptions_To_aws_InstanceMetadataOptions(in *InstanceMetadataOptions, out *aws.InstanceMetadataOptions, s conversion.Scope) error {
	out.HTTPTokens = (*aws.HTTPTokensValue)(unsafe.Pointer(in.HTTPTokens))
	out.HTTPPutResponseHopLimit = (*int64)(unsafe.Pointer(in.HTTPPutResponseHopLimit))
	return nil
}

// Convert_v1alpha1_InstanceMetadataOptions_To_aws_InstanceMetadataOptions is an autogenerated conversion function.
func Convert_v1alpha1_InstanceMetadataOptions_To_aws_InstanceMetadataOptions(in *InstanceMetadataOptions, out *aws.InstanceMetadataOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceMetadataOptions_To_aws_InstanceMetadataOptions(in, out, s)
}

func autoConvert_aws_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(in *aws.InstanceMetadataOptions, out *InstanceMetadataOptions, s conversion.Scope) error {
	out.HTTPTokens = (*HTTPTokensValue)(unsafe.Pointer(in.HTTPTokens))
	out.HTTPPutResponseHopLimit = (*int64)(unsafe.Pointer(in.HTTPPutResponseHopLimit))
	return nil
}

// Convert_aws_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions is an autogenerated conversion function.
func Convert_aws_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(in *aws.InstanceMetadataOptions, out *InstanceMetadataOptions, s conversion.Scope) error {
	return autoConvert_aws_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(in, out, s)
}

func autoConvert_v1alpha1_InstanceProfile_To_aws_InstanceProfile(in *InstanceProfile, out *aws.InstanceProfile, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_InstanceProfile_To_aws_InstanceProfile is an autogenerated conversion function.
func Convert_v1alpha1_InstanceProfile_To_aws_InstanceProfile(in *InstanceProfile, out *aws.InstanceProfile, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceProfile_To_aws_InstanceProfile(in, out, s)
}

func autoConvert_aws_InstanceProfile_To_v1alpha1_InstanceProfile(in *aws.InstanceProfile, out *InstanceProfile, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.Name = in.Name
	return nil
}

// Convert_aws_InstanceProfile_To_v1alpha1_InstanceProfile is an autogenerated conversion function.
func Convert_aws_InstanceProfile_To_v1alpha1_InstanceProfile(in *aws.InstanceProfile, out *InstanceProfile, s conversion.Scope) error {
	return autoConvert_aws_InstanceProfile_To_v1alpha1_InstanceProfile(in, out, s)
}

func autoConvert_v1alpha1_LoadBalancerControllerConfig_To_aws_LoadBalancerControllerConfig(in *LoadBalancerControllerConfig, out *aws.LoadBalancerControllerConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IngressClassName = (*string)(unsafe.Pointer(in.IngressClassName))
	return nil
}

// Convert_v1alpha1_LoadBalancerControllerConfig_To_aws_LoadBalancerControllerConfig is an autogenerated conversion function.
func Convert_v1alpha1_LoadBalancerControllerConfig_To_aws_LoadBalancerControllerConfig(in *LoadBalancerControllerConfig, out *aws.LoadBalancerControllerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_LoadBalancerControllerConfig_To_aws_LoadBalancerControllerConfig(in, out, s)
}

func autoConvert_aws_LoadBalancerControllerConfig_To_v1alpha1_LoadBalancerControllerConfig(in *aws.LoadBalancerControllerConfig, out *LoadBalancerControllerConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IngressClassName = (*string)(unsafe.Pointer(in.IngressClassName))
	return nil
}

// Convert_aws_LoadBalancerControllerConfig_To_v1alpha1_LoadBalancerControllerConfig is an autogenerated conversion function.
func Convert_aws_LoadBalancerControllerConfig_To_v1alpha1_LoadBalancerControllerConfig(in *aws.LoadBalancerControllerConfig, out *LoadBalancerControllerConfig, s conversion.Scope) error {
	return autoConvert_aws_LoadBalancerControllerConfig_To_v1alpha1_LoadBalancerControllerConfig(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_aws_MachineImage(in *MachineImage, out *aws.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.AMI = in.AMI
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	out.Capabilities = *(*v1beta1.Capabilities)(unsafe.Pointer(&in.Capabilities))
	return nil
}

// Convert_v1alpha1_MachineImage_To_aws_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_aws_MachineImage(in *MachineImage, out *aws.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_aws_MachineImage(in, out, s)
}

func autoConvert_aws_MachineImage_To_v1alpha1_MachineImage(in *aws.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.AMI = in.AMI
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	out.Capabilities = *(*v1beta1.Capabilities)(unsafe.Pointer(&in.Capabilities))
	return nil
}

// Convert_aws_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_aws_MachineImage_To_v1alpha1_MachineImage(in *aws.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_aws_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageFlavor_To_aws_MachineImageFlavor(in *MachineImageFlavor, out *aws.MachineImageFlavor, s conversion.Scope) error {
	out.Regions = *(*[]aws.RegionAMIMapping)(unsafe.Pointer(&in.Regions))
	out.Capabilities = *(*v1beta1.Capabilities)(unsafe.Pointer(&in.Capabilities))
	return nil
}

// Convert_v1alpha1_MachineImageFlavor_To_aws_MachineImageFlavor is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageFlavor_To_aws_MachineImageFlavor(in *MachineImageFlavor, out *aws.MachineImageFlavor, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageFlavor_To_aws_MachineImageFlavor(in, out, s)
}

func autoConvert_aws_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(in *aws.MachineImageFlavor, out *MachineImageFlavor, s conversion.Scope) error {
	out.Regions = *(*[]RegionAMIMapping)(unsafe.Pointer(&in.Regions))
	out.Capabilities = *(*v1beta1.Capabilities)(unsafe.Pointer(&in.Capabilities))
	return nil
}

// Convert_aws_MachineImageFlavor_To_v1alpha1_MachineImageFlavor is an autogenerated conversion function.
func Convert_aws_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(in *aws.MachineImageFlavor, out *MachineImageFlavor, s conversion.Scope) error {
	return autoConvert_aws_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_aws_MachineImageVersion(in *MachineImageVersion, out *aws.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Regions = *(*[]aws.RegionAMIMapping)(unsafe.Pointer(&in.Regions))
	out.CapabilityFlavors = *(*[]aws.MachineImageFlavor)(unsafe.Pointer(&in.CapabilityFlavors))
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_aws_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_aws_MachineImageVersion(in *MachineImageVersion, out *aws.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_aws_MachineImageVersion(in, out, s)
}

func autoConvert_aws_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *aws.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Regions = *(*[]RegionAMIMapping)(unsafe.Pointer(&in.Regions))
	out.CapabilityFlavors = *(*[]MachineImageFlavor)(unsafe.Pointer(&in.CapabilityFlavors))
	return nil
}

// Convert_aws_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_aws_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *aws.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_aws_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_aws_MachineImages(in *MachineImages, out *aws.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]aws.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_aws_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_aws_MachineImages(in *MachineImages, out *aws.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_aws_MachineImages(in, out, s)
}

func autoConvert_aws_MachineImages_To_v1alpha1_MachineImages(in *aws.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_aws_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_aws_MachineImages_To_v1alpha1_MachineImages(in *aws.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_aws_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_Networks_To_aws_Networks(in *Networks, out *aws.Networks, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPC_To_aws_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Zones = *(*[]aws.Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_v1alpha1_Networks_To_aws_Networks is an autogenerated conversion function.
func Convert_v1alpha1_Networks_To_aws_Networks(in *Networks, out *aws.Networks, s conversion.Scope) error {
	return autoConvert_v1alpha1_Networks_To_aws_Networks(in, out, s)
}

func autoConvert_aws_Networks_To_v1alpha1_Networks(in *aws.Networks, out *Networks, s conversion.Scope) error {
	if err := Convert_aws_VPC_To_v1alpha1_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Zones = *(*[]Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_aws_Networks_To_v1alpha1_Networks is an autogenerated conversion function.
func Convert_aws_Networks_To_v1alpha1_Networks(in *aws.Networks, out *Networks, s conversion.Scope) error {
	return autoConvert_aws_Networks_To_v1alpha1_Networks(in, out, s)
}

func autoConvert_v1alpha1_RegionAMIMapping_To_aws_RegionAMIMapping(in *RegionAMIMapping, out *aws.RegionAMIMapping, s conversion.Scope) error {
	out.Name = in.Name
	out.AMI = in.AMI
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_v1alpha1_RegionAMIMapping_To_aws_RegionAMIMapping is an autogenerated conversion function.
func Convert_v1alpha1_RegionAMIMapping_To_aws_RegionAMIMapping(in *RegionAMIMapping, out *aws.RegionAMIMapping, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegionAMIMapping_To_aws_RegionAMIMapping(in, out, s)
}

func autoConvert_aws_RegionAMIMapping_To_v1alpha1_RegionAMIMapping(in *aws.RegionAMIMapping, out *RegionAMIMapping, s conversion.Scope) error {
	out.Name = in.Name
	out.AMI = in.AMI
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_aws_RegionAMIMapping_To_v1alpha1_RegionAMIMapping is an autogenerated conversion function.
func Convert_aws_RegionAMIMapping_To_v1alpha1_RegionAMIMapping(in *aws.RegionAMIMapping, out *RegionAMIMapping, s conversion.Scope) error {
	return autoConvert_aws_RegionAMIMapping_To_v1alpha1_RegionAMIMapping(in, out, s)
}

func autoConvert_v1alpha1_Role_To_aws_Role(in *Role, out *aws.Role, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.ARN = in.ARN
	return nil
}

// Convert_v1alpha1_Role_To_aws_Role is an autogenerated conversion function.
func Convert_v1alpha1_Role_To_aws_Role(in *Role, out *aws.Role, s conversion.Scope) error {
	return autoConvert_v1alpha1_Role_To_aws_Role(in, out, s)
}

func autoConvert_aws_Role_To_v1alpha1_Role(in *aws.Role, out *Role, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.ARN = in.ARN
	return nil
}

// Convert_aws_Role_To_v1alpha1_Role is an autogenerated conversion function.
func Convert_aws_Role_To_v1alpha1_Role(in *aws.Role, out *Role, s conversion.Scope) error {
	return autoConvert_aws_Role_To_v1alpha1_Role(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroup_To_aws_SecurityGroup(in *SecurityGroup, out *aws.SecurityGroup, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.ID = in.ID
	return nil
}

// Convert_v1alpha1_SecurityGroup_To_aws_SecurityGroup is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroup_To_aws_SecurityGroup(in *SecurityGroup, out *aws.SecurityGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroup_To_aws_SecurityGroup(in, out, s)
}

func autoConvert_aws_SecurityGroup_To_v1alpha1_SecurityGroup(in *aws.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.ID = in.ID
	return nil
}

// Convert_aws_SecurityGroup_To_v1alpha1_SecurityGroup is an autogenerated conversion function.
func Convert_aws_SecurityGroup_To_v1alpha1_SecurityGroup(in *aws.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	return autoConvert_aws_SecurityGroup_To_v1alpha1_SecurityGroup(in, out, s)
}

func autoConvert_v1alpha1_Storage_To_aws_Storage(in *Storage, out *aws.Storage, s conversion.Scope) error {
	out.ManagedDefaultClass = (*bool)(unsafe.Pointer(in.ManagedDefaultClass))
	return nil
}

// Convert_v1alpha1_Storage_To_aws_Storage is an autogenerated conversion function.
func Convert_v1alpha1_Storage_To_aws_Storage(in *Storage, out *aws.Storage, s conversion.Scope) error {
	return autoConvert_v1alpha1_Storage_To_aws_Storage(in, out, s)
}

func autoConvert_aws_Storage_To_v1alpha1_Storage(in *aws.Storage, out *Storage, s conversion.Scope) error {
	out.ManagedDefaultClass = (*bool)(unsafe.Pointer(in.ManagedDefaultClass))
	return nil
}

// Convert_aws_Storage_To_v1alpha1_Storage is an autogenerated conversion function.
func Convert_aws_Storage_To_v1alpha1_Storage(in *aws.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_aws_Storage_To_v1alpha1_Storage(in, out, s)
}

func autoConvert_v1alpha1_Subnet_To_aws_Subnet(in *Subnet, out *aws.Subnet, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.ID = in.ID
	out.Zone = in.Zone
	return nil
}

// Convert_v1alpha1_Subnet_To_aws_Subnet is an autogenerated conversion function.
func Convert_v1alpha1_Subnet_To_aws_Subnet(in *Subnet, out *aws.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha1_Subnet_To_aws_Subnet(in, out, s)
}

func autoConvert_aws_Subnet_To_v1alpha1_Subnet(in *aws.Subnet, out *Subnet, s conversion.Scope) error {
	out.Purpose = in.Purpose
	out.ID = in.ID
	out.Zone = in.Zone
	return nil
}

// Convert_aws_Subnet_To_v1alpha1_Subnet is an autogenerated conversion function.
func Convert_aws_Subnet_To_v1alpha1_Subnet(in *aws.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_aws_Subnet_To_v1alpha1_Subnet(in, out, s)
}

func autoConvert_v1alpha1_VPC_To_aws_VPC(in *VPC, out *aws.VPC, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	out.GatewayEndpoints = *(*[]string)(unsafe.Pointer(&in.GatewayEndpoints))
	return nil
}

// Convert_v1alpha1_VPC_To_aws_VPC is an autogenerated conversion function.
func Convert_v1alpha1_VPC_To_aws_VPC(in *VPC, out *aws.VPC, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPC_To_aws_VPC(in, out, s)
}

func autoConvert_aws_VPC_To_v1alpha1_VPC(in *aws.VPC, out *VPC, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	out.GatewayEndpoints = *(*[]string)(unsafe.Pointer(&in.GatewayEndpoints))
	return nil
}

// Convert_aws_VPC_To_v1alpha1_VPC is an autogenerated conversion function.
func Convert_aws_VPC_To_v1alpha1_VPC(in *aws.VPC, out *VPC, s conversion.Scope) error {
	return autoConvert_aws_VPC_To_v1alpha1_VPC(in, out, s)
}

func autoConvert_v1alpha1_VPCStatus_To_aws_VPCStatus(in *VPCStatus, out *aws.VPCStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Subnets = *(*[]aws.Subnet)(unsafe.Pointer(&in.Subnets))
	out.SecurityGroups = *(*[]aws.SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	return nil
}

// Convert_v1alpha1_VPCStatus_To_aws_VPCStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCStatus_To_aws_VPCStatus(in *VPCStatus, out *aws.VPCStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCStatus_To_aws_VPCStatus(in, out, s)
}

func autoConvert_aws_VPCStatus_To_v1alpha1_VPCStatus(in *aws.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Subnets = *(*[]Subnet)(unsafe.Pointer(&in.Subnets))
	out.SecurityGroups = *(*[]SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	return nil
}

// Convert_aws_VPCStatus_To_v1alpha1_VPCStatus is an autogenerated conversion function.
func Convert_aws_VPCStatus_To_v1alpha1_VPCStatus(in *aws.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	return autoConvert_aws_VPCStatus_To_v1alpha1_VPCStatus(in, out, s)
}

func autoConvert_v1alpha1_Volume_To_aws_Volume(in *Volume, out *aws.Volume, s conversion.Scope) error {
	out.IOPS = (*int64)(unsafe.Pointer(in.IOPS))
	out.Throughput = (*int64)(unsafe.Pointer(in.Throughput))
	return nil
}

// Convert_v1alpha1_Volume_To_aws_Volume is an autogenerated conversion function.
func Convert_v1alpha1_Volume_To_aws_Volume(in *Volume, out *aws.Volume, s conversion.Scope) error {
	return autoConvert_v1alpha1_Volume_To_aws_Volume(in, out, s)
}

func autoConvert_aws_Volume_To_v1alpha1_Volume(in *aws.Volume, out *Volume, s conversion.Scope) error {
	out.IOPS = (*int64)(unsafe.Pointer(in.IOPS))
	out.Throughput = (*int64)(unsafe.Pointer(in.Throughput))
	return nil
}

// Convert_aws_Volume_To_v1alpha1_Volume is an autogenerated conversion function.
func Convert_aws_Volume_To_v1alpha1_Volume(in *aws.Volume, out *Volume, s conversion.Scope) error {
	return autoConvert_aws_Volume_To_v1alpha1_Volume(in, out, s)
}

func autoConvert_v1alpha1_WorkerConfig_To_aws_WorkerConfig(in *WorkerConfig, out *aws.WorkerConfig, s conversion.Scope) error {
	out.NodeTemplate = (*extensionsv1alpha1.NodeTemplate)(unsafe.Pointer(in.NodeTemplate))
	out.Volume = (*aws.Volume)(unsafe.Pointer(in.Volume))
	out.DataVolumes = *(*[]aws.DataVolume)(unsafe.Pointer(&in.DataVolumes))
	out.IAMInstanceProfile = (*aws.IAMInstanceProfile)(unsafe.Pointer(in.IAMInstanceProfile))
	out.InstanceMetadataOptions = (*aws.InstanceMetadataOptions)(unsafe.Pointer(in.InstanceMetadataOptions))
	out.CpuOptions = (*aws.CpuOptions)(unsafe.Pointer(in.CpuOptions))
	return nil
}

// Convert_v1alpha1_WorkerConfig_To_aws_WorkerConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkerConfig_To_aws_WorkerConfig(in *WorkerConfig, out *aws.WorkerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerConfig_To_aws_WorkerConfig(in, out, s)
}

func autoConvert_aws_WorkerConfig_To_v1alpha1_WorkerConfig(in *aws.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	out.NodeTemplate = (*extensionsv1alpha1.NodeTemplate)(unsafe.Pointer(in.NodeTemplate))
	out.Volume = (*Volume)(unsafe.Pointer(in.Volume))
	out.DataVolumes = *(*[]DataVolume)(unsafe.Pointer(&in.DataVolumes))
	out.IAMInstanceProfile = (*IAMInstanceProfile)(unsafe.Pointer(in.IAMInstanceProfile))
	out.InstanceMetadataOptions = (*InstanceMetadataOptions)(unsafe.Pointer(in.InstanceMetadataOptions))
	out.CpuOptions = (*CpuOptions)(unsafe.Pointer(in.CpuOptions))
	return nil
}

// Convert_aws_WorkerConfig_To_v1alpha1_WorkerConfig is an autogenerated conversion function.
func Convert_aws_WorkerConfig_To_v1alpha1_WorkerConfig(in *aws.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	return autoConvert_aws_WorkerConfig_To_v1alpha1_WorkerConfig(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_aws_WorkerStatus(in *WorkerStatus, out *aws.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]aws.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_aws_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_aws_WorkerStatus(in *WorkerStatus, out *aws.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_aws_WorkerStatus(in, out, s)
}

func autoConvert_aws_WorkerStatus_To_v1alpha1_WorkerStatus(in *aws.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_aws_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_aws_WorkerStatus_To_v1alpha1_WorkerStatus(in *aws.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_aws_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}

func autoConvert_v1alpha1_WorkloadIdentityConfig_To_aws_WorkloadIdentityConfig(in *WorkloadIdentityConfig, out *aws.WorkloadIdentityConfig, s conversion.Scope) error {
	out.RoleARN = in.RoleARN
	return nil
}

// Convert_v1alpha1_WorkloadIdentityConfig_To_aws_WorkloadIdentityConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadIdentityConfig_To_aws_WorkloadIdentityConfig(in *WorkloadIdentityConfig, out *aws.WorkloadIdentityConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadIdentityConfig_To_aws_WorkloadIdentityConfig(in, out, s)
}

func autoConvert_aws_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(in *aws.WorkloadIdentityConfig, out *WorkloadIdentityConfig, s conversion.Scope) error {
	out.RoleARN = in.RoleARN
	return nil
}

// Convert_aws_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig is an autogenerated conversion function.
func Convert_aws_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(in *aws.WorkloadIdentityConfig, out *WorkloadIdentityConfig, s conversion.Scope) error {
	return autoConvert_aws_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(in, out, s)
}

func autoConvert_v1alpha1_Zone_To_aws_Zone(in *Zone, out *aws.Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.Internal = in.Internal
	out.Public = in.Public
	out.Workers = in.Workers
	out.ElasticIPAllocationID = (*string)(unsafe.Pointer(in.ElasticIPAllocationID))
	return nil
}

// Convert_v1alpha1_Zone_To_aws_Zone is an autogenerated conversion function.
func Convert_v1alpha1_Zone_To_aws_Zone(in *Zone, out *aws.Zone, s conversion.Scope) error {
	return autoConvert_v1alpha1_Zone_To_aws_Zone(in, out, s)
}

func autoConvert_aws_Zone_To_v1alpha1_Zone(in *aws.Zone, out *Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.Internal = in.Internal
	out.Public = in.Public
	out.Workers = in.Workers
	out.ElasticIPAllocationID = (*string)(unsafe.Pointer(in.ElasticIPAllocationID))
	return nil
}

// Convert_aws_Zone_To_v1alpha1_Zone is an autogenerated conversion function.
func Convert_aws_Zone_To_v1alpha1_Zone(in *aws.Zone, out *Zone, s conversion.Scope) error {
	return autoConvert_aws_Zone_To_v1alpha1_Zone(in, out, s)
}
