apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-load-balancer-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
