apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-load-balancer-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.resources.gardener.cloud/from-all-webhook-targets-allowed-ports: '[{"protocol":"TCP","port":9443}]'
  name: {{ template "aws-load-balancer-controller.webhookService" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      name: webhook-server
      targetPort: 9443
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
