name: Prepare-Release

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    - name: prepare-release
      shell: bash
      run: |
        set -eu
        make generate
