// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package imagevector

import _ "github.com/gardener/gardener-extension-provider-aws/pkg/imagevector/packrd"
