apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: tm-extension-aws-
  namespace: default
spec:
  ttlSecondsAfterFinished: 172800 # 2 days
  {{- if .Values.revision }}
  locationSets:
  - default: true
    name: provider-aws
    locations:
    - type: git
      repo: https://github.com/gardener/gardener-extension-provider-aws.git
      revision: {{ .Values.revision }}
  {{- end }}

  config:
  - name: ACCESS_KEY_ID
    type: env
    valueFrom:
      secretKeyRef:
        name: shoot-operator-aws
        key: accessKeyID
  - name: SECRET_ACCESS_KEY
    type: env
    valueFrom:
      secretKeyRef:
        name: shoot-operator-aws
        key: secretAccessKey
  - name: DNS_ACCESS_KEY_ID
    type: env
    valueFrom:
      secretKeyRef:
        name: route53-operator-aws
        key: accessKeyID
  - name: DNS_SECRET_ACCESS_KEY
    type: env
    valueFrom:
      secretKeyRef:
        name: route53-operator-aws
        key: secretAccessKey
  - name: ACCESS_KEY_ID_BACKUP
    type: env
    valueFrom:
      secretKeyRef:
        name: backup-operator-aws
        key: accessKeyID
  - name: SECRET_ACCESS_KEY_BACKUP
    type: env
    valueFrom:
      secretKeyRef:
        name: backup-operator-aws
        key: secretAccessKey

  testflow:
  - name: infrastructure-test-tf
    definition:
      name: infrastructure-test
      config:
        - name: REGION
          type: env
          value: eu-west-1
        - name: RECONCILER
          type: env
          value: tf
  - name: infrastructure-test-flow
    definition:
      name: infrastructure-test
      config:
        - name: REGION
          type: env
          value: eu-west-1
        - name: RECONCILER
          type: env
          value: flow
  - name: infrastructure-test-migrate
    definition:
      name: infrastructure-test
      config:
        - name: REGION
          type: env
          value: eu-west-1
        - name: RECONCILER
          type: env
          value: migrate
  - name: infrastructure-test-recover
    definition:
      name: infrastructure-test
      config:
      - name: REGION
        type: env
        value: eu-west-1
      - name: RECONCILER
        type: env
        value: recover
  - name: backupbucket-test
    definition:
      name: backupbucket-test
      config:
        - name: REGION
          type: env
          value: eu-west-1
        - name: LOG_LEVEL
          type: env
          value: debug
        - name: USE_EXISTING_CLUSTER
          type: env
          value: "true"
  - name: bastion-test
    definition:
      name: bastion-test
      config:
      - name: REGION
        type: env
        value: eu-west-1
  - name: dnsrecord-test
    definition:
      name: dnsrecord-test
      config:
      - name: USE_EXISTING_CLUSTER
        type: env
        value: "true"
