---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-ipam-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-ipam-controller
subjects:
- kind: ServiceAccount
  name: aws-ipam-controller
  namespace: kube-system
