apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-ipam-controller
  namespace: kube-system
rules:
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  resourceNames:
    - aws-ipam-controller-leader-election
  verbs:
    - get
    - update
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
    - update
