apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-ipam-controller
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: aws-ipam-controller
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-ipam-controller
