---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups:
  - core.gardener.cloud
  resources:
  - shoots
  - cloudprofiles
  - secretbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
