{
 "title": "Cloud Controller Manager",
 "tags": [
  "controlplane",
  "seed",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "severity", "label": "Severity", "query": "INFO,WARN,ERR,DBG,NOTICE,FATAL" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "UP Time",
   "type": "singlestat",
   "description": "Current uptime status.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"cloud-controller-manager\"} == 1) / sum(up{job=\"cloud-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage and shows the requests and limits.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"cloud-controller-manager-(.+)\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"cloud-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"cloud-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"cloud-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"cloud-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"cloud-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{pod_name=~\"cloud-controller-manager-(.+)\", severity=~\"$severity\"} |~ \"$search\""
    }
   ]
  }
 ]
}