images:
  aws-custom-route-controller: image-repository:image-tag

replicas: 1

podAnnotations: {}

podLabels: {}

providerName: provider-foo

metricsPort: 10258
healthzPort: 10259

podNetwork: 192.168.0.0/16
region: region

vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"

resources:
  requests:
    cpu: 30m
    memory: 50Mi

enabled: false