---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aws-ipam-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: aws-ipam-controller
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: kubernetes
      role: aws-ipam-controller
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.Version }}
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
