---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-ipam-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-ipam-controller
subjects:
- kind: ServiceAccount
  name: aws-ipam-controller
  namespace: {{ .Release.Namespace }}
