name: AI-assisted PR review
on:
  pull_request_target:
    types: [labeled]

jobs:
  review:
    if: ${{ github.event.label.name == 'ai/review' }}
    name: PR Review
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: write
    steps:
      - uses: SAP/ai-assisted-github-actions/pr-review@v3
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: gpt-4o
          exclude-files: package-lock.json
          display-mode: review-comment-delta