name: Build
on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: snapshot

  component-descriptor:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: collect-component-descriptor
        uses: gardener/cc-utils/.github/actions/merge-ocm-fragments@master
        with:
          component-descriptor-artefact: base-component-descriptor
          outdir: /tmp/ocm
      - name: upload-component-descriptor
        run: |
          python -m ocm upload \
            --file /tmp/ocm/component-descriptor.yaml \
            --blobs-dir /tmp/ocm/blobs.d
