name: Build
on:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: snapshot
    permissions:
      contents: read
      packages: write
      id-token: write

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/post-build.yaml@master
    needs:
      - build
    permissions:
      id-token: write
      contents: write
