name: Release
on:
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: release

  release-to-github-and-bump:
    uses: gardener/cc-utils/.github/workflows/release.yaml@master
    needs:
      - build
    secrets:
      github-app-secret-key: ${{ secrets.GARDENER_GITHUB_ACTIONS_PRIVATE_KEY }}
    with:
      release-commit-target: branch
      next-version: bump-minor
