name: Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        type: choice
        options:
          - set-prerelease
          - noop
        description: 'Select whether to modify the release version.'
      next-version:
        type: choice
        options:
          - bump-minor
          - bump-patch
        description: 'Select the type of version bump for the next release.'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    with:
      mode: release
      release-version: ${{ inputs.release-version }}

  integration-tests:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/run-integrationtests.yaml

  release-to-github-and-bump:
    uses: gardener/cc-utils/.github/workflows/release.yaml@master
    needs:
      - build
      - integration-tests
    secrets: inherit
    with:
      release-commit-target: branch
      next-version: ${{ inputs.next-version }}
      next-version-callback-action-path: .github/actions/prepare-release
      slack-channel-id: C9CEBQPGE # #sap-tech-gardener
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write

  close-release-milestone:
    if: ${{ inputs.next-version == 'bump-minor' && inputs.release-version == 'set-prerelease' }}
    needs:
      - build
      - release-to-github-and-bump
    uses: ./.github/workflows/close-milestone.yaml
    with:
      name: ${{ needs.release-to-github-and-bump.outputs.component-descriptor.version }}
      strip_patch: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  create-release-branch:
    if: ${{ inputs.next-version == 'bump-minor' && inputs.release-version == 'set-prerelease' }}
    needs:
      - build
      - release-to-github-and-bump
    uses: ./.github/workflows/create-branch.yaml
    with:
      version: ${{ needs.release-to-github-and-bump.outputs.component-descriptor.version }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
