apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: aws-lb-readvertiser
  namespace: {{ .Release.Namespace }}
  labels:
    app: aws-lb-readvertiser
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: aws-lb-readvertiser
  template:
    metadata:
      labels:
        gardener.cloud/role: controlplane
        app: aws-lb-readvertiser
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-public-networks: allowed
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: aws-lb-readvertiser
        image: {{ index .Values.images "aws-lb-readvertiser" }}
        imagePullPolicy: IfNotPresent
        args:
        {{- if .Values.useTokenRequestor }}
        - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        {{- else }}
        - --kubeconfig=/var/lib/aws-lb-readvertiser/kubeconfig
        {{- end }}
        - --elb-dns-name={{ .Values.domain }}
        - --refresh-period=5
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 40m
            memory: 40Mi
        volumeMounts:
        {{- if .Values.useTokenRequestor }}
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
        {{- else }}
        - name: aws-lb-readvertiser
          mountPath: /var/lib/aws-lb-readvertiser
        {{- end }}
      volumes:
      {{- if .Values.useTokenRequestor }}
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
                - key: kubeconfig
                  path: kubeconfig
              name: generic-token-kubeconfig
              optional: false
          - secret:
              items:
                - key: token
                  path: token
              name: shoot-access-aws-lb-readvertiser
              optional: false
      {{- else }}
      - name: aws-lb-readvertiser
        secret:
          secretName: aws-lb-readvertiser
      {{- end }}
